# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"j\n\x0ePredictRequest\x12\x15\n\rSepalLengthCm\x18\x01 \x01(\x02\x12\x14\n\x0cSepalWidthCm\x18\x02 \x01(\x02\x12\x15\n\rPetalLengthCm\x18\x03 \x01(\x02\x12\x14\n\x0cPetalWidthCm\x18\x04 \x01(\x02\"\"\n\x0fPredictResponse\x12\x0f\n\x07Species\x18\x01 \x01(\t2A\n\x05Model\x12\x38\n\x07Predict\x12\x15.model.PredictRequest\x1a\x16.model.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREDICTREQUEST']._serialized_start=22
  _globals['_PREDICTREQUEST']._serialized_end=128
  _globals['_PREDICTRESPONSE']._serialized_start=130
  _globals['_PREDICTRESPONSE']._serialized_end=164
  _globals['_MODEL']._serialized_start=166
  _globals['_MODEL']._serialized_end=231
# @@protoc_insertion_point(module_scope)
